#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Commandline options
typeset OPERATOR_VERSION=$1
typeset RM_VERSION=$2
typeset K8S_VERSION=$3

# Variable(s)
typeset RANCHER_SRV=$(hostname -f)
typeset RANCHER_PWD=rancherpassword
typeset RM_KUBECONFIG=${HOME}/.kube/config-rancher
typeset RM_FLAGS

# Operator repository
if [[ -z "${OPERATOR_REPO}" ]]; then
  [[ "${OPERATOR_VERSION}" == "stable" ]] \
    && OPERATOR_REPO=oci://registry.suse.com/rancher \
    || OPERATOR_REPO=oci://registry.opensuse.org/isv/rancher/elemental/${OPERATOR_VERSION:-dev}/charts/rancher
fi

# NOTE: SKIP_* should be defined before calling the script if needed!

# Install K8s
# K3s: v1.26.10+k3s2
# RKE2: v1.26.10+rke2r2
(( SKIP_K8S )) || InstallK8s ${K8S_VERSION:=v1.26.10+k3s2}

# Configure Helm repos
(( SKIP_HELM )) || ConfigureHelm

# Install certificate
(( SKIP_CERT )) || InstallCert

# Install Rancher Manager
if ! (( SKIP_RM )); then
  InstallRM ${RM_VERSION}

  # Get already generated local cluster kubeconfig
  GetLocalConfig

  # Install Elemental Operator
  (( SKIP_ELEMENTAL )) || InstallElementalOperator

  # Install rancher-backup-operator
  # NOTE: BACKUP_RESTORE_VERSION should be defined before calling the script if needed!
  if ! (( SKIP_BACKUP )); then
    [[ "${K8S_VERSION}" =~ "rke2" ]] || InstallBackupOperator ${BACKUP_RESTORE_VERSION}
  fi
fi
