#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Variable(s)
typeset RM_PWD=rancherpassword
typeset RM_KUBECONFIG=${HOME}/.kube/config
typeset RM_FLAGS

# Set the server variable if empty
[[ -z "${RM_SRV}" ]] && RM_SRV=$(hostname -f)

# Operator repository
if [[ -z "${ELEMENTAL_REPO}" ]]; then
  [[ "${ELEMENTAL_VERSION}" == "stable" ]] \
    && ELEMENTAL_REPO=oci://registry.suse.com/rancher \
    || ELEMENTAL_REPO=oci://registry.opensuse.org/isv/rancher/elemental/${ELEMENTAL_VERSION:-dev}/charts/rancher
fi

# NOTE: SKIP_* should be defined before calling the script if needed!

# Install K8s
(( SKIP_K8S )) || InstallK8s ${K8S_VERSION:=v1.28.10+k3s1}

# Configure Helm repos
(( SKIP_HELM )) || ConfigureHelm

# Install certificate
(( SKIP_CERT )) || InstallCert

# Install Rancher Manager
if ! (( SKIP_RM )); then
  InstallRM ${RM_VERSION:-stable}

  # Get already generated local cluster kubeconfig
  GetLocalConfig

  # Install Elemental Operator
  (( SKIP_ELEMENTAL )) || InstallElementalOperator

  # Install rancher-backup-operator
  # NOTE: BACKUP_RESTORE_VERSION should be defined before calling the script if needed!
  if ! (( SKIP_BACKUP )); then
    [[ "${K8S_VERSION}" =~ "rke2" ]] || InstallBackupOperator ${BACKUP_RESTORE_VERSION}
  fi
fi
