#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Variable(s)
typeset RM_PWD=rancherpassword
typeset RM_KUBECONFIG=${HOME}/.kube/config
typeset RM_FLAGS

# Default versions used
: ELEMENTAL_VERSION=${ELEMENTAL_VERSION:=maintenance/6.2}
: K8S_VERSION=${K8S_VERSION:=v1.34.2+k3s1}
: RANCHER_VERSION=${RANCHER_VERSION:=stable/latest}
#: RANCHER_VERSION=${RANCHER_VERSION:=prime/latest}

# Set the server variable if empty
[[ -z "${RM_SRV}" ]] && RM_SRV=$(hostname -f)

# Operator repository
if [[ -z "${ELEMENTAL_REPO}" ]]; then
  # If empty, install Elemental Stable version by default
  [[ "${ELEMENTAL_VERSION}" == "stable" || -z "${ELEMENTAL_VERSION}" ]] \
    && ELEMENTAL_REPO=oci://registry.suse.com/rancher \
    || ELEMENTAL_REPO=oci://registry.opensuse.org/isv/rancher/elemental/${ELEMENTAL_VERSION}/charts/rancher
fi

# NOTE: SKIP_* should be defined before calling the script if needed!

# Install K8s
(( SKIP_K8S )) || InstallK8s ${K8S_VERSION}

# Configure Helm repos
(( SKIP_HELM )) || ConfigureHelm "" true

# Install certificate
(( SKIP_CERT )) || InstallCert

# Install Rancher Manager
if ! (( SKIP_RM )); then
  InstallRancher ${RANCHER_VERSION}

  # Install Elemental Operator
  (( SKIP_ELEMENTAL )) || InstallElementalOperator
fi

# Force Elemental Operator installation if needed
(( FORCE_ELEMENTAL )) && InstallElementalOperator

# Install rancher-backup-operator
(( SKIP_BACKUP )) || InstallBackupOperator ${BACKUP_RESTORE_VERSION}

# Get already generated local cluster kubeconfig, should be done at the end
(( SKIP_RM )) || GetLocalConfig
