#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Variable(s)
typeset RM_SRV=$(hostname -f)
typeset RM_PWD=rancherpassword

# Upgrade Rancher Manager to defined version
InstallRM ${RM_VERSION:-latest}
