#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Variable(s)
typeset RM_PWD=rancherpassword

# Set the server variable if empty
[[ -z "${RM_SRV}" ]] && RM_SRV=$(hostname -f)

# Upgrade Rancher Manager to defined version
InstallRancher ${RANCHER_VERSION:-latest}
