#!/bin/bash

# Load functions library
source $(realpath ${HOME}/bin)/elemental-functions

# Operator repository
if [[ -z "${ELEMENTAL_REPO}" ]]; then
  [[ "${ELEMENTAL_VERSION}" == "stable" ]] \
    && ELEMENTAL_REPO=oci://registry.suse.com/rancher \
    || ELEMENTAL_REPO=oci://registry.opensuse.org/isv/rancher/elemental/${ELEMENTAL_VERSION:-dev}/charts/rancher
fi

# Sync Helm repos
helm repo update || quit "Error while updating Helm repos!" 1

# Upgrade elemental-operator
InstallElementalOperator
